default_stages: [commit]
repos:
- repo: git://github.com/antonbabenko/pre-commit-terraform
  rev: v1.45.0
  hooks:
    - id: terraform_fmt
    - id: terraform_validate
    - id: terraform_docs
    - id: terraform_tflint
    - id: terragrunt_fmt
    - id: terragrunt_validate
    - id: terraform_tfsec
      files: '\.tf'